import AsyncStorage from '@react-native-async-storage/async-storage';
import * as SecureStore from 'expo-secure-store';
import * as ExpoCrypto from 'expo-crypto';
import CryptoJS from 'crypto-js';
import { classifyStoredValue, LEGACY_PLAIN_PREFIX } from './secureStoragePolicy';

const MASTER_KEY_ALIAS = 'FiltreAI_Master_Key';
const LEGACY_FALLBACK_KEY = 'fallback_offline_key_for_filtre_ai_v1';

export class SecureStorageUnavailableError extends Error {
  constructor(readonly storageKey: string) {
    super('Cihazın güvenli depolama özelliği kullanılamıyor.');
    this.name = 'SecureStorageUnavailableError';
  }
}

export class SecureStorage {
  private static async randomHex(byteCount: number): Promise<string> {
    const bytes = await ExpoCrypto.getRandomBytesAsync(byteCount);
    return Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('');
  }

  private static encryptionKey(masterKey: string): CryptoJS.lib.WordArray {
    const keyHex = /^[a-f0-9]{64}$/i.test(masterKey)
      ? masterKey
      : CryptoJS.SHA256(masterKey).toString(CryptoJS.enc.Hex);
    return CryptoJS.enc.Hex.parse(keyHex);
  }

  /**
   * Cihazın donanımsal güvenli alanından (Keystore/Keychain) şifreleme anahtarını getirir.
   * Eğer yoksa yeni ve rastgele bir anahtar oluşturup güvenli alana kaydeder.
   */
  private static async getMasterKey(): Promise<string> {
    let key = await SecureStore.getItemAsync(MASTER_KEY_ALIAS);
    if (!key) {
      key = await this.randomHex(32);
      await SecureStore.setItemAsync(MASTER_KEY_ALIAS, key, {
        keychainAccessible: SecureStore.WHEN_UNLOCKED,
      });
    }
    return key;
  }

  private static async migrateLegacyPlaintext(
    key: string,
    value: string,
  ): Promise<string | null> {
    try {
      await this.setItem(key, value);
      return value;
    } catch {
      await AsyncStorage.removeItem(key);
      return null;
    }
  }

  /**
   * Veriyi şifreleyerek AsyncStorage'a kaydeder (Data at Rest Security)
   */
  static async setItem(key: string, value: string): Promise<void> {
    try {
      const masterKey = await this.getMasterKey();
      const ivHex = await this.randomHex(16);
      const encryptedValue = CryptoJS.AES.encrypt(value, this.encryptionKey(masterKey), {
        iv: CryptoJS.enc.Hex.parse(ivHex),
      }).toString();
      await AsyncStorage.setItem(key, `v2:${ivHex}:${encryptedValue}`);
    } catch (error) {
      console.warn(`Şifreli depolama kullanılamadı; veri kaydedilmedi: ${key}`);
      throw new SecureStorageUnavailableError(key);
    }
  }

  /**
   * AsyncStorage'daki şifreli veriyi çözerek geri getirir.
   */
  static async getItem(key: string): Promise<string | null> {
    try {
      const encryptedValue = await AsyncStorage.getItem(key);
      if (!encryptedValue) return null;

      const storedValueKind = classifyStoredValue(encryptedValue);
      if (storedValueKind === 'legacy-plain') {
        return this.migrateLegacyPlaintext(
          key,
          encryptedValue.slice(LEGACY_PLAIN_PREFIX.length),
        );
      }

      if (storedValueKind === 'legacy-json') {
        return this.migrateLegacyPlaintext(key, encryptedValue);
      }

      const masterKey = await this.getMasterKey();

      // v2 uses an IV generated by expo-crypto. Legacy entries retain the
      // previous decryption path so existing local data remains readable.
      const [version, ivHex, ciphertext] = encryptedValue.split(':', 3);
      const bytes = storedValueKind === 'encrypted-v2' && ivHex && ciphertext
        ? CryptoJS.AES.decrypt(ciphertext, this.encryptionKey(masterKey), {
            iv: CryptoJS.enc.Hex.parse(ivHex),
          })
        : CryptoJS.AES.decrypt(encryptedValue, masterKey);
      const originalText = bytes.toString(CryptoJS.enc.Utf8);

      // Eğer şifreleme anahtarı değişmişse veya eski şifresiz veri varsa boş dönebilir,
      // bu durumu ele alıyoruz (Migration support).
      if (!originalText) return null;
      return originalText;
    } catch (error) {
      const rawValue = await AsyncStorage.getItem(key);
      if (!rawValue) return null;

      const storedValueKind = classifyStoredValue(rawValue);
      if (storedValueKind === 'legacy-plain') {
        return this.migrateLegacyPlaintext(
          key,
          rawValue.slice(LEGACY_PLAIN_PREFIX.length),
        );
      }
      if (storedValueKind === 'legacy-json') {
        return this.migrateLegacyPlaintext(key, rawValue);
      }

      try {
        const [version, ivHex, ciphertext] = rawValue.split(':', 3);
        const legacyBytes = version === 'v2' && ivHex && ciphertext
          ? CryptoJS.AES.decrypt(ciphertext, this.encryptionKey(LEGACY_FALLBACK_KEY), {
              iv: CryptoJS.enc.Hex.parse(ivHex),
            })
          : CryptoJS.AES.decrypt(rawValue, LEGACY_FALLBACK_KEY);
        const legacyText = legacyBytes.toString(CryptoJS.enc.Utf8);
        if (legacyText) {
          return this.migrateLegacyPlaintext(key, legacyText);
        }
      } catch {
        // Bozuk veya farklı anahtarla şifrelenmiş veriyi güvenli biçimde yok say.
      }

      console.warn(`Depolanan veri okunamadı ve varsayılan değere dönülecek: ${key}`);
      return null;
    }
  }

  /**
   * AsyncStorage'dan veriyi siler.
   */
  static async removeItem(key: string): Promise<void> {
    await AsyncStorage.removeItem(key);
  }
}
