import AsyncStorage from '@react-native-async-storage/async-storage';
import * as SecureStore from 'expo-secure-store';
import * as ExpoCrypto from 'expo-crypto';
import CryptoJS from 'crypto-js';

const MASTER_KEY_ALIAS = 'FiltreAI_Master_Key';
const PLAIN_FALLBACK_PREFIX = 'plain:v1:';
const LEGACY_FALLBACK_KEY = 'fallback_offline_key_for_filtre_ai_v1';

export class SecureStorage {
  private static async randomHex(byteCount: number): Promise<string> {
    const bytes = await ExpoCrypto.getRandomBytesAsync(byteCount);
    return Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('');
  }

  private static encryptionKey(masterKey: string): CryptoJS.lib.WordArray {
    const keyHex = /^[a-f0-9]{64}$/i.test(masterKey)
      ? masterKey
      : CryptoJS.SHA256(masterKey).toString(CryptoJS.enc.Hex);
    return CryptoJS.enc.Hex.parse(keyHex);
  }

  /**
   * Cihazın donanımsal güvenli alanından (Keystore/Keychain) şifreleme anahtarını getirir.
   * Eğer yoksa yeni ve rastgele bir anahtar oluşturup güvenli alana kaydeder.
   */
  private static async getMasterKey(): Promise<string> {
    let key = await SecureStore.getItemAsync(MASTER_KEY_ALIAS);
    if (!key) {
      key = await this.randomHex(32);
      await SecureStore.setItemAsync(MASTER_KEY_ALIAS, key, {
        keychainAccessible: SecureStore.WHEN_UNLOCKED,
      });
    }
    return key;
  }

  /**
   * Veriyi şifreleyerek AsyncStorage'a kaydeder (Data at Rest Security)
   */
  static async setItem(key: string, value: string): Promise<void> {
    try {
      const masterKey = await this.getMasterKey();
      const ivHex = await this.randomHex(16);
      const encryptedValue = CryptoJS.AES.encrypt(value, this.encryptionKey(masterKey), {
        iv: CryptoJS.enc.Hex.parse(ivHex),
      }).toString();
      await AsyncStorage.setItem(key, `v2:${ivHex}:${encryptedValue}`);
    } catch (error) {
      console.warn(`Şifreli depolama kullanılamadı, uygulama depolama alanına geçiliyor: ${key}`);
      await AsyncStorage.setItem(key, `${PLAIN_FALLBACK_PREFIX}${value}`);
    }
  }

  /**
   * AsyncStorage'daki şifreli veriyi çözerek geri getirir.
   */
  static async getItem(key: string): Promise<string | null> {
    try {
      const encryptedValue = await AsyncStorage.getItem(key);
      if (!encryptedValue) return null;

      if (encryptedValue.startsWith(PLAIN_FALLBACK_PREFIX)) {
        return encryptedValue.slice(PLAIN_FALLBACK_PREFIX.length);
      }

      if (encryptedValue.startsWith('{') || encryptedValue.startsWith('[')) {
        await this.setItem(key, encryptedValue);
        return encryptedValue;
      }

      const masterKey = await this.getMasterKey();

      // v2 uses an IV generated by expo-crypto. Legacy entries retain the
      // previous decryption path so existing local data remains readable.
      const [version, ivHex, ciphertext] = encryptedValue.split(':', 3);
      const bytes = version === 'v2' && ivHex && ciphertext
        ? CryptoJS.AES.decrypt(ciphertext, this.encryptionKey(masterKey), {
            iv: CryptoJS.enc.Hex.parse(ivHex),
          })
        : CryptoJS.AES.decrypt(encryptedValue, masterKey);
      const originalText = bytes.toString(CryptoJS.enc.Utf8);

      // Eğer şifreleme anahtarı değişmişse veya eski şifresiz veri varsa boş dönebilir,
      // bu durumu ele alıyoruz (Migration support).
      if (!originalText) return null;
      return originalText;
    } catch (error) {
      const rawValue = await AsyncStorage.getItem(key);
      if (!rawValue) return null;

      if (rawValue.startsWith(PLAIN_FALLBACK_PREFIX)) {
        return rawValue.slice(PLAIN_FALLBACK_PREFIX.length);
      }

      try {
        const [version, ivHex, ciphertext] = rawValue.split(':', 3);
        const legacyBytes = version === 'v2' && ivHex && ciphertext
          ? CryptoJS.AES.decrypt(ciphertext, this.encryptionKey(LEGACY_FALLBACK_KEY), {
              iv: CryptoJS.enc.Hex.parse(ivHex),
            })
          : CryptoJS.AES.decrypt(rawValue, LEGACY_FALLBACK_KEY);
        const legacyText = legacyBytes.toString(CryptoJS.enc.Utf8);
        if (legacyText) {
          await this.setItem(key, legacyText);
          return legacyText;
        }
      } catch {
        // Bozuk veya farklı anahtarla şifrelenmiş veriyi güvenli biçimde yok say.
      }

      console.warn(`Depolanan veri okunamadı ve varsayılan değere dönülecek: ${key}`);
      return null;
    }
  }

  /**
   * AsyncStorage'dan veriyi siler.
   */
  static async removeItem(key: string): Promise<void> {
    await AsyncStorage.removeItem(key);
  }
}
